config/routes.rb
Rails.application.routes.draw do
  # we have overwritten devise's methods for registration with our own 
  devise_for :users, :controllers => {:registrations => "registrations"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'home#index'

  resources :post

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
  end

  devise_scope :user do
    get 'signup', to: 'devise/registrations#new'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user

    has_many :comments

    has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  #dependent destroy will remove all things if user is destroyed
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    def index 
    end
    
end

app/controllers/post_controller.rb
class PostController < ApplicationController

    def index
        @post = current_user.posts.build
        @posts = Post.all
    end

    def show
        #@posts = Post.all
      
    end



    def create 
        @post = current_user.posts.build(post_params)
        @post.user = current_user
        @post.save
        redirect_to post_index_path
    end 

    private
    def post_params
      params.require(:post).permit(:title, :image)
    end

    def current_user_id
        current_user[:id]
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    private

    def sign_up_params
      params.require(:user).permit( :name, 
                                    :email, 
                                    :password, 
                                    :password_confirmation)
    end
  
    def account_update_params
      params.require(:user).permit( :name, 
                                    :email, 
                                    :password, 
                                    :password_confirmation, 
                                    :current_password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/views/home/index.html.erb
<h1> welcome to wondering wombat wanders </h1>

app/views/layouts/_navigation_bar.html.erb
<%= link_to 'home', root_path, class: 'navbar-brand' %>
<% if user_signed_in? %>
  <li>
  <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
  </li>
<% else %>
  <li>
  <%= link_to('Login',login_path)  %>
  </li>
  <li>
  <%= link_to('Signup', signup_path)  %>
  </li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WombatWonders</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation_bar' %>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/post/_add_post.html.erb
<%=form_for(@post, as: :post, url: post_index_path, html: { multipart: true }) do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
    <%= f.label :image %>
    <%= f.file_field :image, class: 'form-control'%>
    <%= f.submit 'Upload Photo', class: 'btn btn-default' %>
<% end %>

app/views/post/index.html.erb
<%= render "add_post" %>
<h1>posts</h1>


<% @posts.each do |post| %>
    <%= image_tag(post.image, style:'width:60%') %>
    <p><%= post.title %></p>
    <p><%= post.user.name %></p>
<% end %>